project:
  type: website
  output-dir: docs

website:
  title: "Raster & GDAL Processing"

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    theme: flatly
    embed-resources: false
